#ifndef MOD_AUTH_PAKE_APACHE2_MODULE_INIT_H
#define MOD_AUTH_PAKE_APACHE2_MODULE_INIT_H

#include <httpd.h>
#include "ap_config.h"
#include "httpd.h"
#include "http_config.h"
#include "http_core.h"
#include "http_request.h"
#include "http_log.h"
#include "http_protocol.h"
#include "apr_uri.h"
#include "util_md5.h"
#include "apr_shm.h"
#include "apr_rmm.h"
#include "ap_provider.h"

#include "mod_auth.h"

#include "apache2_module.h"
#include "pake.h"


static unsigned char auth_pake_secret[SECRET_LEN];

module AP_MODULE_DECLARE_DATA auth_pake_module;


int initialize_module(apr_pool_t *p, apr_pool_t *plog,
                      apr_pool_t *ptemp, server_rec *s);
void *create_auth_pake_dir_config(apr_pool_t *p, char *dir);

const char *set_realm(cmd_parms *cmd, void *config, const char *realm);

/* struct to hold the configuration info */

typedef struct auth_pake_config_struct {
    const char  *dir_name;
    authn_provider_list *providers;
    const char  *realm;
    const char *pakefile;
    BN_CTX      *bn_ctx;
    struct pake_info *pake;
} auth_pake_config_rec;


static const command_rec auth_pake_cmds[] =
{
    AP_INIT_TAKE1("AuthName", set_realm, NULL, OR_AUTHCFG,
     "The authentication realm (e.g. \"Members Only\")"),
    AP_INIT_TAKE1("PAKEFile", ap_set_file_slot, 
                  (void *)APR_OFFSETOF(auth_pake_config_rec, pakefile), OR_AUTHCFG, 
                  "text file containing usernames, pi_0, and L (generated by htpake)"),
    {NULL}
};


#endif // MOD_AUTH_PAKE_APACHE2_MODULE_INIT_H
